# Welcome to Jekyll!


# In addition to these settings, there is a file _data/tokens-template.yml
# that you'll want to customize for your site. It's named 'tokens' because
# that was it's original purpose, but because tokens.yml is .gitexcluded, it's
# a good place to store your site-specific data that you'd rather not have
# forked or cloned. Of course, that means you'd want to back it up elsewhere.

# Also, for your post bylines, add author info for yourself in `_data/authors.yml`.
# (Using that method instead of site.owner, in case your posts get cloned with your repo.)

# Site settings
title: Est-ce que c'est du travail ?
description: Documentation d'itinérance
owner:
  name: Thomas Parisot et Noémie Girard
  email: hello@estcequecestdutravail.xyz
  url: http://estcequecestdutravail.xyz
first_published: 2018 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://estcequecestdutravail.xyz" # the base hostname & protocol for your site

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title:  
  text: "Est-ce que c'est du travail ?", c'est la question qu'on se pose en souriant quand on s'aperçoit qu'on discute du revenu de base avant le petit déjeuner, est-ce que c'est un sujet de discussion comme un autre ou est-ce que c'est un sujet qui émane de notre rapport quotidien au travail ?
  Quand on se passionne pour des sujets et que la discussion déborde aux matinées et aux soirées, est-ce que c'est du travail ?
  
  Suivez ici les points d'étapes dans notre recherche d'un endroit où vivre et être utile.
# - title for your blog's featured posts
features-title: Featured articles
# - displayed at the bottom
closing-head: À bientôt
closing-para: 

# on all pages (and the first three you list display with greeting, if included)
social:
  twitter: https://twitter.com/noeems
  github: https://github.com/noeems/estcequecestdutravail.xyz
  email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# if you use this repo's `ruby compose.rb` script to initiate new posts, put the
# command to invoke your editor here. (I didn't spend time dealing with spaces
# and full paths of the various OSes in compose.rb. For my Windows
# environment, I just put a subl.cmd file in my PATH that points to the full
# path to Sublime's subl.exe.) Also, put your most common post extension.
compose:
  editor: subl
  extension: md

# choose where to put back and next links:
# top, bottom, both, none
navlinks: bottom

# expecting more works? mark your list as in-progress
works_in_progress: yes

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post

# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []
